### ISSUE TITLE
please help me with attached problems

### ISSUE THREAD

**Issue by dapeng313** [Jarcionek/Codility#1]
Some hours ago. I've toptal 2nd test with Codility.
Problems are aboves.
I didnt passed about it.
But i wanna know solutions.
Please give me your help with your talented skills.
Thanks.
[test.docx](https://github.com/Jarcionek/Codility/files/1165160/test.docx)

**Comment by Jarcionek** [comment]
Could you please write your problems here rather than providing a link to the file?

**Comment by dapeng313** [comment]
i've captured problems and saved it

**Comment by Jarcionek** [comment]
Sorry, but I won't open a file from unknown person due to security reasons.

**Comment by dapeng313** [comment]
how can i contact with you?

**Comment by Jarcionek** [comment]
You can describe the problems here rather than attaching a file.

**Comment by dapeng313** [comment]
1.

![image](https://user-images.githubusercontent.com/8647385/28462582-6cd1ad14-6e4e-11e7-8b5f-03e19ab343f1.png)
![image](https://user-images.githubusercontent.com/8647385/28462597-77b3db3a-6e4e-11e7-8484-9a528afbd4a5.png)

2.
![image](https://user-images.githubusercontent.com/8647385/28462605-853c8c98-6e4e-11e7-8a4d-5869c4560db3.png)
![image](https://user-images.githubusercontent.com/8647385/28462617-8de844fe-6e4e-11e7-82b3-9813800b1b9d.png)

3.
![image](https://user-images.githubusercontent.com/8647385/28462631-94dd59ac-6e4e-11e7-93e1-569b609c808b.png)

![image](https://user-images.githubusercontent.com/8647385/28462636-98895754-6e4e-11e7-8ee2-1320fc89af37.png)

**Comment by Jarcionek** [comment]
1:
Given that time complexity limit is O(nlogn) you could just create a new sorted array and compare the two. If elements at only two indices differ, that would mean only one swap so the function should return true. There might be some edge cases but I cannot see any at the moment.

I think this problem can be solved in O(n) time complexity and O(1) memory but that would be more difficult solution:
- iterate over array to find two elements A[x] that are greater than A[x+1]
- either keep iterating over an array until you find third such element - if you do the answer is false
- or swap these two and check whether array is sorted

**Comment by Jarcionek** [comment]
2:
Using recursion you have to traverse the entire tree - start with going all the way to the left, then back off and start taking rights until you reach every leaf that way. You need to keep a current count of turns and just compare it against max whenever you reach a leaf.

**Comment by Jarcionek** [comment]
3:
Instead of waiting until the monkey can do X jumps, always try to jump the farthest to the right every time tick. Look at that image, at time 0, monkey can reach position 2 (jump from -1 to 2), then it cannot make a jump so you move the time one tick forward and check again. So in pseudocode:
- check array between current monkey's position M and M+D (you need to compare elements against the current time)
- if no jump available, move time forward by 1 tick and go back to first step
- if monkey can jump to next stone, update M and go back to first step without updating time

I am not sure about time complexity though. It might be something weird like O(N*D) or O(max(N*D, max(A))).
